apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: blue-frontend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blue-frontend
    app.kubernetes.io/part-of: blue-whale
  name: blue-frontend
  namespace: pdave3
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: blue-frontend
    weight: 100
status: {}
